/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Surface tokens
        'surface':                      '#f8f9ff',
        'surface-dim':                  '#cbdbf5',
        'surface-bright':               '#f8f9ff',
        'surface-container-lowest':     '#ffffff',
        'surface-container-low':        '#eff4ff',
        'surface-container':            '#e5eeff',
        'surface-container-high':       '#dce9ff',
        'surface-container-highest':    '#d3e4fe',
        'on-surface':                   '#0b1c30',
        'on-surface-variant':           '#434655',
        'inverse-surface':              '#213145',
        'inverse-on-surface':           '#eaf1ff',
        'surface-tint':                 '#0053db',
        'surface-variant':              '#d3e4fe',
        // Outline tokens
        'outline':                      '#737686',
        'outline-variant':              '#c3c6d7',
        // Primary tokens
        'primary':                      '#004ac6',
        'on-primary':                   '#ffffff',
        'primary-container':            '#2563eb',
        'on-primary-container':         '#eeefff',
        'inverse-primary':              '#b4c5ff',
        'primary-fixed':                '#dbe1ff',
        'primary-fixed-dim':            '#b4c5ff',
        'on-primary-fixed':             '#00174b',
        'on-primary-fixed-variant':     '#003ea8',
        // Secondary tokens
        'secondary':                    '#565e74',
        'on-secondary':                 '#ffffff',
        'secondary-container':          '#dae2fd',
        'on-secondary-container':       '#5c647a',
        'secondary-fixed':              '#dae2fd',
        'secondary-fixed-dim':          '#bec6e0',
        'on-secondary-fixed':           '#131b2e',
        'on-secondary-fixed-variant':   '#3f465c',
        // Tertiary tokens
        'tertiary':                     '#006329',
        'on-tertiary':                  '#ffffff',
        'tertiary-container':           '#007f36',
        'on-tertiary-container':        '#c7ffca',
        'tertiary-fixed':               '#7ffc97',
        'tertiary-fixed-dim':           '#62df7d',
        'on-tertiary-fixed':            '#002109',
        'on-tertiary-fixed-variant':    '#005320',
        // Error tokens
        'error':                        '#ba1a1a',
        'on-error':                     '#ffffff',
        'error-container':              '#ffdad6',
        'on-error-container':           '#93000a',
        // Background tokens
        'background':                   '#f8f9ff',
        'on-background':                '#0b1c30',
      },
      fontFamily: {
        // sans = default Tailwind body font → Be Vietnam Pro
        sans:         ['"Be Vietnam Pro"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'be-vietnam': ['"Be Vietnam Pro"', 'sans-serif'],
        'inter':      ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display':      ['36px', { lineHeight: '44px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg':  ['28px', { lineHeight: '36px', fontWeight: '600', letterSpacing: '-0.015em' }],
        'headline-md':  ['20px', { lineHeight: '28px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-sm':  ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg':      ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':      ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm':      ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md':     ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-sm':     ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'data-metric':  ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.02em' }],
        'data-table':   ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
      borderRadius: {
        'sm':      '0.125rem',
        DEFAULT:   '0.25rem',
        'md':      '0.375rem',
        'lg':      '0.5rem',
        'xl':      '0.75rem',
        'full':    '9999px',
      },
      spacing: {
        'gutter':     '1rem',
        'gutter-lg':  '1.5rem',
        'margin':     '1rem',
        'margin-md':  '1.5rem',
        'margin-lg':  '2rem',
        'space-xs':   '0.25rem',
        'space-sm':   '0.5rem',
        'space-md':   '0.75rem',
        'space-lg':   '1rem',
        'space-xl':   '1.5rem',
        'space-2xl':  '2rem',
      },
      boxShadow: {
        'elevation-1': '0 1px 2px 0 rgba(15,23,42,0.04)',
        'elevation-2': '0 4px 6px -1px rgba(15,23,42,0.08), 0 2px 4px -2px rgba(15,23,42,0.04)',
        'elevation-3': '0 20px 25px -5px rgba(15,23,42,0.1), 0 8px 10px -6px rgba(15,23,42,0.06)',
      },
    },
  },
  plugins: [],
};
