spring.application.name=school-management

# Kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/school_management
spring.datasource.username=school_app
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Chưa muốn tạo bảng tự động
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


server.port=8081
